services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
  server:
    build: .
    ports:
      - 3030:8080
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?schema=public
      - BROKER_URL
      - SECRET
      - CHATBOTS_CONTAINER_URLS
    depends_on:
      - db
